#!/usr/local/bin/perl
# $Id: TEST,v 1.1 2000/09/11 22:14:11 cgilmore Exp $
# This script runs Test::Harness on the tests found under the
# "t" directory.

# First we check if we already are within the "t" directory
unless (-d "base") {
  # try to move into test directory
  chdir "t" or die "Can't chdir: $!";
  
  # fix all relative library locations
  foreach (@INC) {
    $_ = "../$_" unless m,^/,;
  }
}

# Pick up the library files from the ../blib directory
unshift(@INC, "../blib/lib", "../blib/arch");

use Test::Harness;
$Test::Harness::verbose = shift
  if $ARGV[0] =~ /^\d+$/ || $ARGV[0] eq "-v";

if (@ARGV) {
  for (@ARGV) {
    if (-d $_) {
      push(@tests, <$_/*.t>);
    } else {
      $_ .= ".t" unless /\.t$/;
      push(@tests, $_);
    }
  }
} else {
  @tests = (<base/*.t>);
}

runtests @tests;
